### PR TITLE
Symfony commands

### PR DESCRIPTION
**Pull request by mms-uret**

### CODE REVIEW

**Comment by lsmith77** [comment]
maybe a quick fix is to just use the var_dumper component http://symfony.com/doc/current/components/var_dumper/advanced.html#dumpers

**Comment by mms-uret** [comment]
Done.

**Comment by dbu** [comment]
there is a rokka cli client built with the symfony console: https://github.com/rokka-io/rokka-client-php-cli

i am currently refactoring things in there so that we then can use all commands in the cli also in the bundle.

are you adding any commands here that the cli does not provide? if there are, please do a pull request against the [cli library](https://github.com/rokka-io/rokka-client-php-cli) instead.

**Comment by mms-uret** [comment]
ah ok, in this case I close this pull request.

**Pull request closed without merging**
